name: release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    # Solo correr cuando CI haya pasado en un push a main
    if: >-
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: write       # para git tag / changelog
      packages: write       # para publicar en npm
      pull-requests: write  # para comentar PRs si fuera necesario

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install

      - name: Build core package
        run: pnpm -C packages/core build

      - name: Publish core to npm & GitHub
        run: pnpm -C packages/core release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
